import { sliders } from "./sliders.js";
sliders();
import { buttons } from "./buttons.js";
buttons();
import { menu } from "./menu.js";
menu();
import { revealing } from "./revealing_sections.js";
revealing();
import { changeTheme } from "./changeTheme.js";
changeTheme();
